# Generated by Django 3.2.5 on 2022-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1994-04-23'),
            preserve_default=False,
        ),
    ]
